# Data Quality Checks – Logistics Dataset

This notebook performs data quality validation on multiple tables used in the logistics profitability analysis.

Tables included:
- Fact tables: loads, trips, delivery_events
- Cost tables: fuel_purchases, maintenance_records, safety_incidents
- Dimension tables: drivers, trucks, trailers, customers, facilities, routes

The analysis focuses on the following tables that are relevant to the business case:

- Trips
- Loads
- Routes
- Fuel_Purchases
- Maintenance_Records

## Import Libraries

In [307]:
from pathlib import Path
import pandas as pd
import numpy as np

## Load Data

The datasets are stored as CSV files and loaded into pandas DataFrames for validation and cleaning.

In [327]:

folder_path = Path(r"C:\Users\mory_\Downloads\Compressed\Logistic Database")

trips = pd.read_csv(folder_path/'trips.csv')
loads = pd.read_csv(folder_path / "loads.csv")
routes = pd.read_csv(folder_path / "routes.csv")
FUEL_PURCHASES = pd.read_csv(folder_path / "FUEL_PURCHASES.csv")
MAINTENANCE_RECORDS = pd.read_csv(folder_path / "MAINTENANCE_RECORDS.csv")

## Initial Data Inspection

In [319]:
## Data Inspection and Data Quality Checks

def quality_check(df, name):
    
    print(f"\n---- {name} ----")
    
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    
    print("\nMissing values:")
    print(df.isnull().sum())
    
    print("\nDuplicate rows:", df.duplicated().sum())

    print("\nChecking Data Types:")
    print(df.dtypes)

    print("\nChecking Invalid Values and basic Statistics:")
    print(df.describe())

In [317]:

quality_check(trips, "Trips Table")
quality_check(loads, "Loads Table")
quality_check(routes, "Routes Table")
quality_check(FUEL_PURCHASES, "FUEL_PURCHASES Table")
quality_check(MAINTENANCE_RECORDS, "MAINTENANCE_RECORDS Table")

---- Trips Table ----
Rows: 85410
Columns: 12

Missing values:
trip_id                     0
load_id                     0
driver_id                1714
truck_id                 1672
trailer_id               1680
dispatch_date               0
actual_distance_miles       0
actual_duration_hours       0
fuel_gallons_used           0
average_mpg                 0
idle_time_hours             0
trip_status                 0
dtype: int64

Duplicate rows: 0

Checking Data Types:
trip_id                   object
load_id                   object
driver_id                 object
truck_id                  object
trailer_id                object
dispatch_date             object
actual_distance_miles      int64
actual_duration_hours    float64
fuel_gallons_used        float64
average_mpg              float64
idle_time_hours          float64
trip_status               object
dtype: object

Checking Invalid Values and basic Statistics:
       actual_distance_miles  actual_duration_hours  fuel_gallons_used  \
count           85410.000000           85410.000000       85410.000000
mean             1430.268130              25.014674         221.827422
std               801.931973              14.191944         126.558874
min                90.000000               1.400000          12.000000
25%               717.000000              12.600000         111.800000
50%              1297.500000              23.000000         204.500000
75%              2147.000000              36.900000         326.400000
max              3391.000000              67.800000         611.900000

        average_mpg  idle_time_hours
count  85410.000000     85410.000000
mean       6.501463         7.010783
std        0.578091         2.882488
min        5.500000         2.000000
25%        6.000000         4.500000
50%        6.500000         7.000000
75%        7.000000         9.500000
max        7.500000        12.000000

---- Loads Table ----
Rows: 85410
Columns: 12

Missing values:
load_id                0
customer_id            0
route_id               0
load_date              0
load_type              0
weight_lbs             0
pieces                 0
revenue                0
fuel_surcharge         0
accessorial_charges    0
load_status            0
booking_type           0
dtype: int64

Duplicate rows: 0

Checking Data Types:
load_id                 object
customer_id             object
route_id                object
load_date               object
load_type               object
weight_lbs               int64
pieces                   int64
revenue                float64
fuel_surcharge         float64
accessorial_charges      int64
load_status             object
booking_type            object
dtype: object

Checking Invalid Values and basic Statistics:
         weight_lbs        pieces       revenue  fuel_surcharge  \
count  85410.000000  85410.000000  85410.000000    85410.000000
mean   27477.495305     14.470530   3073.712683      350.972119
std    10095.421857      8.070077   1883.127436      218.034684
min    10000.000000      1.000000    125.930000       13.800000
25%    18724.000000      7.000000   1443.215000      161.530000
50%    27482.000000     14.000000   2827.985000      314.640000
75%    36190.000000     21.000000   4323.157500      499.180000
max    45000.000000     28.000000   8125.220000      891.820000

       accessorial_charges
count         85410.000000
mean             71.643836
std              70.018823
min               0.000000
25%               0.000000
50%              50.000000
75%             100.000000
max             200.000000

---- Routes Table ----
Rows: 58
Columns: 9

Missing values:
route_id                  0
origin_city               0
origin_state              0
destination_city          0
destination_state         0
typical_distance_miles    0
base_rate_per_mile        0
fuel_surcharge_rate       0
typical_transit_days      0
dtype: int64

Duplicate rows: 0

Checking Data Types:
route_id                   object
origin_city                object
origin_state               object
destination_city           object
destination_state          object
typical_distance_miles      int64
base_rate_per_mile        float64
fuel_surcharge_rate       float64
typical_transit_days        int64
dtype: object

Checking Invalid Values and basic Statistics:
       typical_distance_miles  base_rate_per_mile  fuel_surcharge_rate  \
count               58.000000           58.000000            58.000000
mean              1391.500000            2.196724             0.248793
std                782.833209            0.368788             0.061817
min                 92.000000            1.520000             0.150000
25%                700.750000            1.902500             0.190000
50%               1271.000000            2.230000             0.245000
75%               2085.250000            2.480000             0.300000
max               3141.000000            2.790000             0.340000

       typical_transit_days
count             58.000000
mean               2.120690
std                1.155879
min                1.000000
25%                1.000000
50%                2.000000
75%                3.000000
max                5.000000

---- FUEL_PURCHASES Table ----
Rows: 196442
Columns: 11

Missing values:
fuel_purchase_id       0
trip_id                0
truck_id            3880
driver_id           3988
purchase_date          0
location_city          0
location_state         0
gallons                0
price_per_gallon       0
total_cost             0
fuel_card_number       0
dtype: int64

Duplicate rows: 0

Checking Data Types:
fuel_purchase_id     object
trip_id              object
truck_id             object
driver_id            object
purchase_date        object
location_city        object
location_state       object
gallons             float64
price_per_gallon    float64
total_cost          float64
fuel_card_number     object
dtype: object

Checking Invalid Values and basic Statistics:
             gallons  price_per_gallon     total_cost
count  196442.000000     196442.000000  196442.000000
mean      124.815660          3.898418     486.621965
std        43.346522          0.436489     178.616665
min        50.000000          3.150000     158.500000
25%        87.200000          3.552000     336.240000
50%       124.700000          3.856000     480.660000
75%       162.400000          4.168000     625.530000
max       200.000000          5.000000     997.900000

---- MAINTENANCE_RECORDS Table ----
Rows: 2920
Columns: 12

Missing values:
maintenance_id         0
truck_id               0
maintenance_date       0
maintenance_type       0
odometer_reading       0
labor_hours            0
labor_cost             0
parts_cost             0
total_cost             0
facility_location      0
downtime_hours         0
service_description    0
dtype: int64

Duplicate rows: 0

Checking Data Types:
maintenance_id          object
truck_id                object
maintenance_date        object
maintenance_type        object
odometer_reading         int64
labor_hours            float64
labor_cost             float64
parts_cost             float64
total_cost             float64
facility_location       object
downtime_hours         float64
service_description     object
dtype: object

Checking Invalid Values and basic Statistics:
       odometer_reading  labor_hours   labor_cost   parts_cost   total_cost  \
count       2920.000000  2920.000000  2920.000000  2920.000000  2920.000000
mean      401534.787671     4.178459   438.529825  1523.995271  1962.525096
std       207093.951665     2.131282   229.989621  1103.739471  1135.418952
min        50156.000000     0.500000    43.280000     0.140000    60.820000
25%       215376.500000     2.300000   242.600000   443.125000   906.752500
50%       407955.000000     4.200000   435.200000  1465.415000  1896.045000
75%       585079.000000     6.000000   622.382500  2489.445000  2938.257500
max       749875.000000     8.000000   976.870000  3498.610000  4426.570000

       downtime_hours
count     2920.000000
mean        24.736473
std         13.312263
min          2.000000
25%         13.300000
50%         24.750000
75%         36.225000
max         48.000000

## Data Cleaning

In [280]:
trips = trips.dropna(subset=["truck_id"])

In [282]:
# check rows with null values
trips[trips.isnull().any(axis=1)].head()

,trip_id,load_id,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,trip_status
66,TRIP00000067,LOAD00000067,NaN,TRK00112,TRL00040,2022-01-01,2433,40.0,427.6,5.69,9.2,Completed
103,TRIP00000104,LOAD00000104,NaN,TRK00114,TRL00013,2022-01-02,1048,18.5,143.2,7.32,4.6,Completed
250,TRIP00000251,LOAD00000251,DRV00009,TRK00052,NaN,2022-01-04,1469,24.7,257.7,5.70,2.8,Completed
256,TRIP00000257,LOAD00000257,NaN,TRK00049,TRL00070,2022-01-04,717,11.5,98.8,7.26,3.1,Completed
271,TRIP00000272,LOAD00000272,DRV00146,TRK00051,NaN,2022-01-04,1883,30.5,326.9,5.76,3.9,Completed

In [286]:
# missing values for FUEL_PURCHASES
FUEL_PURCHASES = FUEL_PURCHASES.dropna(subset=['truck_id'])

In [288]:
FUEL_PURCHASES[FUEL_PURCHASES.isnull().any(axis=1)].head()

,fuel_purchase_id,trip_id,truck_id,driver_id,purchase_date,location_city,location_state,gallons,price_per_gallon,total_cost,fuel_card_number
1,FUEL00000002,TRIP00073723,TRK00013,NaN,2024-08-04 08:00:00,New York,AZ,139.9,3.180,444.88,FC717910
4,FUEL00000005,TRIP00069700,TRK00054,NaN,2024-06-13 09:00:00,Columbus,AZ,185.3,3.422,634.10,FC391024
23,FUEL00000024,TRIP00019599,TRK00051,NaN,2022-09-09 08:00:00,Detroit,NY,94.6,4.987,471.77,FC397584
41,FUEL00000042,TRIP00074788,TRK00039,NaN,2024-08-19 15:00:00,New York,WA,80.0,3.633,290.64,FC376413
51,FUEL00000052,TRIP00008346,TRK00014,NaN,2022-04-19 02:00:00,Charlotte,CO,82.0,3.696,303.07,FC579727

## Export Cleaned Data
Cleaned datasets were saved for further SQL analysis and Power BI dashboard development.

In [290]:
# Save Clean Data
trips.to_csv(folder_path/"trips_clean.csv", index=False)
FUEL_PURCHASES.to_csv(folder_path/'FUEL_PURCHASES_clean.csv',index=False)